# src/state.py
import operator
from typing import Annotated, Dict, List, Literal, Optional

from pydantic import BaseModel, Field
from typing_extensions import TypedDict


# --- Detective Output ---
class Evidence(BaseModel):
    """
    Represents a piece of evidence found by the detective agents.
    """

    goal: str = Field()
    found: bool = Field(description="Whether the artifact exists")
    content: Optional[str] = Field(default=None)
    location: str = Field(
        description="File path or commit hash",
    )
    rationale: str = Field(
        description="Your rationale for your confidence \n"
        "on the evidence you find for this particular goal",
    )
    confidence: float


# --- Judge Output ---
class JudicialOpinion(BaseModel):
    """
    Represents a judge's evaluation of a specific criterion
    based on the evidence presented.
    """

    judge: Literal["Prosecutor", "Defense", "TechLead"]
    criterion_id: str
    score: int = Field(ge=1, le=5)
    argument: str
    cited_evidence: List[str]


# --- Chief Justice Output ---
class CriterionResult(BaseModel):
    """
    Represents the final evaluation of a specific criterion,
    including the judge's opinions and any dissenting views.
    """

    dimension_id: str
    dimension_name: str
    final_score: int = Field(ge=1, le=5)
    judge_opinions: List[JudicialOpinion]
    dissent_summary: Optional[str] = Field(
        default=None,
        description="Required when score variance > 2",
    )
    remediation: str = Field(
        description="Specific file-level instructions " "for improvement",
    )


class AuditReport(BaseModel):
    """
    Represents the final audit report generated by the Chief Justice,
    summarising the overall findings and recommendations.
    """

    repo_url: str
    executive_summary: str
    overall_score: float
    criteria: List[CriterionResult]
    remediation_plan: str


# --- Graph State ---
class AgentState(TypedDict):
    """
    Represents the state of an individual agent, including its name,
    role, and any relevant data it has collected or generated.
    """

    repo_url: str
    pdf_path: str
    rubric_dimensions: List[Dict]
    # Use reducers to prevent parallel agents from overwriting data
    evidences: Annotated[Dict[str, List[Evidence]], operator.ior]
    opinions: Annotated[List[JudicialOpinion], operator.add]
    final_report: AuditReport
