# src/state.py
from typing import Any, Dict, List, Literal, Optional

from langgraph.channels import BinaryOperatorAggregate
from pydantic import BaseModel, Field
from typing_extensions import Annotated


# --- Detective Output ---
class Evidence(BaseModel):
    """Represents a piece of evidence found by the detective agents."""

    goal: str = Field()
    found: bool = Field(description="Whether the artifact exists")
    content: Optional[Any] = Field(
        default=None, description="Structured evidence content (dict, list, or string)."
    )
    location: str = Field(description="File path or commit hash")
    rationale: str = Field(description="Rationale for confidence in the evidence")
    confidence: float


# --- Judge Output ---
class JudicialOpinion(BaseModel):
    """Represents a judge's evaluation of a specific criterion."""

    judge: Literal["Prosecutor", "Defense", "TechLead"]
    criterion_id: str
    score: int = Field(ge=0, le=10)
    argument: str
    cited_evidence: List[str]


# --- Chief Justice Output ---
class CriterionResult(BaseModel):
    """Represents the final evaluation of a specific criterion."""

    dimension_id: str
    dimension_name: str
    final_score: int = Field(ge=1, le=5)
    judge_opinions: List[JudicialOpinion]
    dissent_summary: Optional[str] = Field(
        default=None,
        description="Required when score variance > 2",
    )
    remediation: str = Field(
        description="Specific file-level instructions for improvement"
    )


class AuditReport(BaseModel):
    """Represents the final audit report generated by the Chief Justice."""

    repo_url: str
    executive_summary: str
    overall_score: float
    criteria: List[CriterionResult]
    remediation_plan: str


# --- Merge functions for concurrent updates ---
def merge_opinions(existing, new):
    """Append new JudicialOpinions to the existing list."""
    return (existing or []) + (new or [])


def merge_evidences(existing, new):
    """Merge dicts of evidence lists by extending values under each key."""
    merged = dict(existing or {})
    for k, v in (new or {}).items():
        merged.setdefault(k, []).extend(v)
    return merged


# --- Graph State ---
class AgentState(BaseModel):
    """
    Represents the state of the courtroom graph, validated at runtime.
    """

    repo_url: str
    pdf_path: str
    rubric_dimensions: List[Dict]

    # Must provide both typ and operator
    evidences: Annotated[
        Dict[str, List[Evidence]],
        BinaryOperatorAggregate(typ=dict, operator=merge_evidences),
    ] = {}

    opinions: Annotated[
        List[JudicialOpinion],
        BinaryOperatorAggregate(typ=list, operator=merge_opinions),
    ] = []

    final_report: Optional[AuditReport] = None
